#!/Users/maister/Projects/scripts/dockerPush.py -x run -d pydev:lite -p 8912 8899 --shebang
version: '3.8'

services:
  app:
    image: frantzme/pythondev:lite

    volumes:
      - ..:/sync:cached  

    # Overrides default command so things don't shut down after the process ends.
    command: sh -c "apt-get install git -y && sleep infinity"

